version: "version 3.8"
name: "Book-Store Application"
services:
  catalog-db:
    image: postgres:17-alpine
    container_name: catalog-db
    ports:
      - "15432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass@6888
      - POSTGRES_DB=postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
        resources:
          limits:
            memory: 500m
